routes/web.php
<?php

use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home');

// Route::middleware([
//     'auth:sanctum',
//     config('jetstream.auth_session'),
//     'verified'
// ])->group(function () {
//     Route::get('/dashboard', function () {
//         return view('dashboard');
//     })->name('dashboard');
// });

Route::get('/login', [LoginController::class, 'index'])->name('login');

Route::middleware('admin')->group(function () {
    Route::prefix('admin')->group(function () {
        Route::get('/', [DashboardController::class, 'index'])->name('dashboard');
        Route::resource('/users', UserController::class);
    });
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Fortify\TwoFactorAuthenticatable;
use Laravel\Jetstream\HasProfilePhoto;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens;
    use HasFactory;
    use HasProfilePhoto;
    use Notifiable;
    use TwoFactorAuthenticatable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
        'two_factor_recovery_codes',
        'two_factor_secret',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = [
        'profile_photo_url',
    ];

    public function user_role()
    {
        return $this->belongsTo(UserRole::class, 'role_id', 'id');
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\User;
use App\Models\UserRole;
use Exception;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::where('role_id', '!=', 0)->with('user_role')->get();
        return view('backend.users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user_roles = UserRole::all();
        return view('backend.users.create', compact('user_roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
            $request->validate([
                'email' => 'required|email',
                'password' => 'required|confirmed|min:6',
            ]);


            $user = new User();
            $user->name = $request->input('name');
            $user->email = $request->input('email');
            $user->phone = $request->input('phone');
            $user->role_id = $request->input('role_id') ?? 3;
            $user->user_name = $request->input('username');
            $user->password = Hash::make($request->input('password'));
            $user->save();
            return redirect('/admin/users');
        } catch(Exception $e) {
            return $e->getMessage();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/backend/users/create.blade.php
<x-admin.layouts.master>
    <x-slot:title>Users </x-slot:title>
    <x-slot:pageTitle>Create User </x-slot:pageTitle>
    <div class="card p-4">
        <div class="card-header">
            
           
            <a href="{{route('users.index')}}" class="btn btn-info">User List</a>
        </div>






        <form action="{{route('users.store')}}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="container">
                <div class="row">


                    <div class="col-md-6">
                        <x-admin.utilities.form.input name="name" placeholder="Enter your full name" label="Full Name:" labelFor="name"  id="name" type="text" value="{{ old('name') }}" /> 
                        <x-admin.utilities.form.error name="name" />
                    </div>
                    <div class="col-md-6">
                        <x-admin.utilities.form.input name="username" placeholder="Enter your username" label=" Username:" labelFor="username"  id="username" type="text" value="{{ old('username') }}" /> 
                        <x-admin.utilities.form.error name="username" />
                    </div>

                    <div class="col-md-6">
                        <x-admin.utilities.form.input name="email" placeholder="Enter your Email Address" label="Email:" labelFor="email"  id="email" type="email" value="{{ old('email') }}" /> 
                        <x-admin.utilities.form.error name="email" />
                    </div>

                    <div class="col-md-6">
                        <x-admin.utilities.form.input name="phone" placeholder="Enter your Phone Number" label="Phone Number" labelFor="phone"  id="phone" type="number" value="{{ old('phone') }}" /> 
                        <x-admin.utilities.form.error name="phone" />
                    </div>

                    <div class="col-md-6">
                        <x-admin.utilities.form.input name="password" placeholder="Enter your password" label="Password" labelFor="password"  id="password" type="password" value="{{ old('password') }}" /> 
                        <x-admin.utilities.form.error name="password" />
                    </div>

                    <div class="col-md-6">
                        <x-admin.utilities.form.input name="password_confirmation" placeholder="Confirm Password" label="Confirm Password" labelFor="password_confirmation"  id="password_confirmation" type="password" value="{{ old('password_confirmation') }}" /> 
                        <x-admin.utilities.form.error name="password_confirmation" />
                    </div>
                    
                    <div class="col-md-6">
                        <label for="" class="form-label mt-3">Select Role</label>
                       <select class="form-control" name="role_id" id="">
                            <option value="">Select Role</option>
                            @foreach ($user_roles as $item)
                                <option value="{{ $item->id }}">{{$item->name}}</option>
                            @endforeach
                       </select>
                    </div>
                    

               
                    
                </div>
                <button type="submit" class="btn btn-primary mt-4">Submit</button>
            </div>
           
           
            
        </form>
    </div>

</x-admin.layouts.master>

resources/views/backend/users/index.blade.php
<x-admin.layouts.master>
    <x-slot:title>Users </x-slot:title>
    <x-slot:pageTitle>User List </x-slot:pageTitle>
    <div class="card mb-4">
        <div class="card-header" style="display: flex; justify-content: space-between; align-items:center;">
            <span><i class="fas fa-table me-1"></i>
                DataTable Example</span>
            <a href="{{ route('users.create') }}" class="btn btn-primary">Add New</a>
            
        </div>
        <div class="card-body">
            <table id="datatablesSimple">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Username</th>
                        <th>Phone</th>
                        <th>Email</th>
                        <th>Role</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>Name</th>
                        <th>Username</th>
                        <th>Phone</th>
                        <th>Email</th>
                        <th>Role</th>
                        <th>Action</th>
                    </tr>
                </tfoot>
                <tbody>
                    @foreach ($users as $item)
                        <tr>
                            <td>{{$item->name}}</td>
                            <td>{{$item->user_name}}</td>
                            <td>{{$item->phone}}</td>
                            <td>{{$item->email}}</td>
                            <td>{{$item->user_role->name}}</td>
                            <td>
                                <a href="" class="btn btn-sm btn-primary">Edit</a>
                                <a href="" class="btn btn-sm btn-danger">Delete</a>
                            </td>
                        </tr>
                    @endforeach
                    
                </tbody>
            </table>
        </div>
    </div>
</x-admin.layouts.master>